/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppWorkoutForm {}
  interface AppWorkoutFormAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppWorkoutForm': Components.AppWorkoutForm;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-workout-form': Components.AppWorkoutFormAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppWorkoutFormElement extends Components.AppWorkoutForm, HTMLStencilElement {}
  var HTMLAppWorkoutFormElement: {
    prototype: HTMLAppWorkoutFormElement;
    new (): HTMLAppWorkoutFormElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-workout-form': HTMLAppWorkoutFormElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-workout-form': HTMLAppWorkoutFormElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
